window.sampleOSData = {
  currentStyleId: "style_212",
  currentReviewId: "review_212_second",
  currentUserId: "user_guyao",
  users: [
    { id: "user_guyao", name: "顾瑶", department: "业务部", role: "业务负责人", currentResponsibility: "收到客户信息后发起开发准备", reviewResponsibility: "确认客户邮件、技术包、物料清单、交期和寄样目的", permissions: ["发起开发", "提交意见", "创建问题", "申请寄样"], scope: ["萨洛蒙"], avatarColor: "guyao" },
    { id: "user_guyonghong", name: "顾永宏", department: "业务部", role: "业务负责人", currentResponsibility: "补齐客户要求和交样日期", reviewResponsibility: "补充寄样目的和风险说明", permissions: ["补充资料", "提交意见", "创建问题"], scope: ["萨洛蒙"], avatarColor: "guyonghong" },
    { id: "user_xuhaiyan", name: "徐海燕", department: "打版组", role: "版型评审员", currentResponsibility: "确认版子完整并安排处理", reviewResponsibility: "评审版型、尺寸、公差、结构、纸样与实物一致性", permissions: ["版型评审", "创建问题", "复验问题"], scope: ["版子"], avatarColor: "xu" },
    { id: "user_liweihong", name: "李卫红", department: "打样面料", role: "面料负责人", currentResponsibility: "确认开发样所需面料", reviewResponsibility: "确认面料齐套、颜色、批次和缩率风险", permissions: ["面料确认", "创建问题", "更新状态"], scope: ["面料"], avatarColor: "liweihong" },
    { id: "user_dahong", name: "大红", department: "打样辅料", role: "辅料负责人", currentResponsibility: "确认拉链、扣具、织带等辅料", reviewResponsibility: "确认辅料规格、颜色、功能和齐套性", permissions: ["辅料确认", "创建问题", "更新状态"], scope: ["辅料"], avatarColor: "dahong" },
    { id: "user_wangbu", name: "王部长", department: "开发管理", role: "资料确认人 / 评审负责人", currentResponsibility: "确认资料齐套并推进派发打样", reviewResponsibility: "可主持样衣评审并确认寄样结论", permissions: ["资料确认", "推进打样", "组织评审", "最终放行"], scope: ["准备闸口", "样衣评审"], avatarColor: "wangbu", isGateOwner: true },
    { id: "user_dadai", name: "大戴", department: "打样间", role: "打样派发人", currentResponsibility: "负责普通款式打样人员分配", reviewResponsibility: "反馈普通打样过程异常", permissions: ["派发打样", "普通打样", "提交异常"], scope: ["普通打样"], avatarColor: "dadai" },
    { id: "user_zhangbu", name: "张部长", department: "新长江工厂", role: "压胶开发负责人", currentResponsibility: "确认压胶开发和工艺风险", reviewResponsibility: "评审压胶参数、胶带匹配和量产稳定性", permissions: ["压胶开发", "创建问题", "要求验证"], scope: ["压胶开发"], avatarColor: "zhang", isGateOwner: false },
    { id: "user_xiahongxia", name: "夏红霞", department: "新长江工厂", role: "新长江派发人", currentResponsibility: "负责新长江打样人员分配", reviewResponsibility: "反馈新长江打样执行异常", permissions: ["新长江派发", "派发打样", "提交异常"], scope: ["新长江派发"], avatarColor: "xia" },
    { id: "user_daqian", name: "大前", department: "品质管理", role: "评审负责人", currentResponsibility: "质量判断、问题阻断、整改复验", reviewResponsibility: "主持评审、确认问题闭环、决定普通寄样结论", permissions: ["评审负责人", "复验问题", "最终放行"], scope: ["样衣评审", "质量放行"], avatarColor: "zhao", isGateOwner: true },
    { id: "user_yang", name: "杨总", department: "管理层", role: "例外放行审批人", currentResponsibility: "处理例外放行和重大争议", reviewResponsibility: "批准重大问题下的例外放行", permissions: ["例外放行", "争议裁决"], scope: ["例外放行"], avatarColor: "wangayi", isFinalApprover: true },
    { id: "user_zhao", name: "赵经理", department: "品质部", role: "质量评审员", currentResponsibility: "识别质量问题并复验", reviewResponsibility: "外观、历史问题、测试和复验要求", permissions: ["提交意见", "创建问题", "复验问题"], scope: ["样衣评审"], avatarColor: "zhao" },
    { id: "user_chen", name: "陈工艺", department: "工艺部", role: "工艺评审员", currentResponsibility: "确认工艺可行性", reviewResponsibility: "缝制、压胶、工艺可行性、量产难点", permissions: ["提交意见", "创建问题"], scope: ["样衣评审"], avatarColor: "chen" },
    { id: "user_mike", name: "麦克", department: "工业工程部", role: "工业工程评审员", currentResponsibility: "评估工时瓶颈和量产风险", reviewResponsibility: "工序、工时、夹具专机、产能风险", permissions: ["提交意见"], scope: ["样衣评审"], avatarColor: "mike" },
    { id: "user_lishifu", name: "李师傅", department: "打样部", role: "打样反馈人", currentResponsibility: "上传样衣并反馈打样异常", reviewResponsibility: "资料不清、材料不齐、实际制作异常", permissions: ["提交意见", "创建问题"], scope: ["样衣评审"], avatarColor: "li" },
  ],
  departments: ["业务部", "打版组", "品质部", "工艺部", "工业工程部", "打样部", "打样面料", "打样辅料", "新长江工厂", "压胶车间", "外发打样", "如东工厂", "管理层"],
  roles: ["业务负责人", "版型评审员", "面料负责人", "辅料负责人", "质量评审员", "工艺评审员", "工业工程评审员", "资料确认人", "打样派发人", "压胶开发负责人", "样衣评审员", "评审负责人", "例外放行人", "后台管理员"],
  gateRules: {
    preparationGateOwner: "user_wangbu",
    sampleReviewGateOwner: "user_daqian",
    finalApprover: "user_yang",
    bondingDevelopmentOwner: "user_zhangbu",
    xinchangjiangDispatcher: "user_xiahongxia",
    normalDispatcher: "user_dadai",
  },
  issueLevelRules: {
    minor: { label: "轻微", shipmentRule: "可寄样，但必须记录", systemAction: "不锁寄样按钮" },
    normal: { label: "一般", shipmentRule: "评审负责人判断是否修改后寄样", systemAction: "提示风险" },
    major: { label: "重大", shipmentRule: "默认阻止寄样，除非例外放行", systemAction: "锁定寄样按钮，需例外放行人审批" },
    critical: { label: "严重", shipmentRule: "必须暂停寄样，整改复验后重新评审", systemAction: "锁定寄样按钮，不允许普通放行" },
  },
  sampleLocations: [
    { name: "开发车间", description: "制作或返修中", defaultHolder: "打样部", changeReason: "制作/返修" },
    { name: "样衣间", description: "待评审或保管", defaultHolder: "样衣管理员", changeReason: "待评审/保管" },
    { name: "业务", description: "寄样准备", defaultHolder: "业务负责人", changeReason: "寄样准备" },
    { name: "客户", description: "客户已收到", defaultHolder: "客户", changeReason: "已送样" },
    { name: "快递", description: "寄出途中", defaultHolder: "快递单号", changeReason: "寄出中" },
    { name: "新长江", description: "新长江执行打样", defaultHolder: "夏红霞", changeReason: "压胶打样" },
    { name: "压胶车间", description: "压胶验证", defaultHolder: "张部长", changeReason: "压胶验证" },
    { name: "待返修", description: "问题整改中", defaultHolder: "责任部门", changeReason: "问题整改" },
    { name: "已寄出", description: "交样完成", defaultHolder: "业务", changeReason: "交样完成" },
  ],
  sampleLocationOptions: [
    { id: "xinchangjiang_sample_room", label: "新长江工厂打样间", recommendedRoute: "bonding_xinchangjiang" },
    { id: "office_sample_room", label: "事务所打样间", recommendedRoute: "normal" },
    { id: "outsourced_sample", label: "外发打样", recommendedRoute: "outsourced" },
    { id: "rudong_factory_sample_room", label: "如东工厂打样间", recommendedRoute: "rudong_factory" },
  ],
  sampleRoutes: {
    normal: "普通款式",
    bonding_xinchangjiang: "压胶 / 新长江款式",
    outsourced: "外发款式",
    rudong_factory: "如东工厂款式",
  },
  samplePhases: {
    first_sample: "一次样",
    second_sample: "二次样",
    third_sample: "三次样",
    sms: "SMS / 销售样",
    pp: "PP / 产前样",
    qc_sample: "QC 样",
    top_sample: "TOP 样",
  },
  routeRules: {
    normal: { label: "普通款式", nodes: ["业务收资料", "版子/面料/辅料并行准备", "王部长确认资料", "大戴分配打样", "打样完成", "样衣评审"] },
    bonding_xinchangjiang: { label: "压胶 / 新长江款式", nodes: ["业务收资料", "版子/面料/辅料并行准备", "王部长确认资料", "张部长确认压胶开发", "夏红霞分配打样", "新长江/压胶打样完成", "样衣评审"] },
    outsourced: { label: "外发款式", nodes: ["业务收资料", "版子/面料/辅料并行准备", "王部长确认资料", "外发负责人确认", "外发打样完成", "样衣评审"] },
    rudong_factory: { label: "如东工厂款式", nodes: ["业务收资料", "版子/面料/辅料并行准备", "王部长确认资料", "如东工厂负责人确认", "如东打样完成", "样衣评审"] },
  },
  ruleVersion: { name: "Sample OS Rules V0.3", updatedAt: "2026-06-29", updatedBy: "Yang", status: "草稿" },
  workers: [
    { id: "worker_liayi", name: "李阿姨", route: "普通打样", skill: "梭织 / 修改", status: "可派发", taskCount: 1, lastCompletedAt: "昨天完成", avatarColor: "liayi" },
    { id: "worker_zhangayi", name: "张阿姨", route: "普通打样", skill: "针织 / 小样验证", status: "忙碌", taskCount: 3, lastCompletedAt: "今天 16:00", avatarColor: "zhangayi" },
    { id: "worker_wangayi", name: "王阿姨", route: "普通打样", skill: "梭织 / 返修", status: "可派发", taskCount: 0, lastCompletedAt: "06-28 完成", avatarColor: "wangayi" },
    { id: "worker_zhuxiaoli", name: "朱晓丽", route: "新长江压胶", skill: "压胶 / 小样验证", status: "可派发", taskCount: 2, lastCompletedAt: "今天上午", avatarColor: "zhuxiaoli" },
  ],
  departmentDetails: [
    { name: "业务部", owner: "顾瑶", participatesInReview: true, receivesNotification: true, issueTypes: ["客户需求", "寄样风险"], defaultReviewer: "顾瑶" },
    { name: "打版组", owner: "徐海燕", participatesInReview: true, receivesNotification: true, issueTypes: ["版型", "尺寸"], defaultReviewer: "徐海燕" },
    { name: "品质部", owner: "赵经理", participatesInReview: true, receivesNotification: true, issueTypes: ["外观", "测试", "复验"], defaultReviewer: "赵经理" },
    { name: "工艺部", owner: "陈工艺", participatesInReview: true, receivesNotification: true, issueTypes: ["缝制", "压胶", "工艺风险"], defaultReviewer: "陈工艺" },
    { name: "工业工程部", owner: "麦克", participatesInReview: true, receivesNotification: true, issueTypes: ["工时", "瓶颈", "产能"], defaultReviewer: "麦克" },
    { name: "打样部", owner: "李师傅", participatesInReview: true, receivesNotification: true, issueTypes: ["打样异常", "资料不清"], defaultReviewer: "李师傅" },
    { name: "打样面料", owner: "李卫红", participatesInReview: false, receivesNotification: true, issueTypes: ["面料齐套", "材料替代"], defaultReviewer: "李卫红" },
    { name: "打样辅料", owner: "大红", participatesInReview: false, receivesNotification: true, issueTypes: ["辅料齐套", "替代料"], defaultReviewer: "大红" },
    { name: "新长江工厂", owner: "夏红霞", participatesInReview: true, receivesNotification: true, issueTypes: ["压胶执行", "派发异常"], defaultReviewer: "夏红霞" },
    { name: "管理层", owner: "杨总", participatesInReview: false, receivesNotification: true, issueTypes: ["例外放行", "争议"], defaultReviewer: "杨总" },
  ],
  permissionMatrix: [
    { role: "业务负责人", permissions: ["发起开发", "提交意见", "创建问题"] },
    { role: "版师", permissions: ["提交意见", "创建问题", "复验问题"] },
    { role: "面料负责人", permissions: ["资料确认", "创建问题"] },
    { role: "辅料负责人", permissions: ["资料确认", "创建问题"] },
    { role: "品质部", permissions: ["提交意见", "创建问题", "复验问题"] },
    { role: "工艺部", permissions: ["提交意见", "创建问题"] },
    { role: "IE 部", permissions: ["提交意见"] },
    { role: "打样部", permissions: ["提交意见", "创建问题"] },
    { role: "资料确认人", permissions: ["资料确认"] },
    { role: "打样派发人", permissions: ["派发打样"] },
    { role: "压胶开发负责人", permissions: ["资料确认", "提交意见", "创建问题"] },
    { role: "新长江派发人", permissions: ["派发打样"] },
    { role: "评审负责人 / Gate Owner", permissions: ["提交意见", "创建问题", "复验问题", "最终放行"] },
    { role: "例外放行人 / Final Approver", permissions: ["例外放行"] },
  ],
  locationTransitions: [
    { from: "开发车间", to: "样衣间", allowedBy: "打样部", scanRequired: true, reasonRequired: false, timeline: true },
    { from: "样衣间", to: "业务", allowedBy: "业务 / 样衣管理员", scanRequired: true, reasonRequired: false, timeline: true },
    { from: "业务", to: "快递", allowedBy: "业务", scanRequired: true, reasonRequired: true, timeline: true },
    { from: "任意位置", to: "待返修", allowedBy: "评审负责人 / 品质", scanRequired: false, reasonRequired: true, timeline: true },
  ],
  trainingStats: { trained: 18, untrained: 7, eligibleReviewers: 25 },
  trainingCards: ["业务评审员职责卡", "版师评审员职责卡", "品质评审员职责卡", "工艺评审员职责卡", "IE 评审员职责卡", "打样评审员职责卡", "问题等级判断训练", "意见转问题示例", "培训小考"],
  styleList: [
    { id: "style_212", styleNo: "212", brand: "萨洛蒙", season: "SS27", styleName: "户外冲锋衣", category: "夹克", route: "normal", currentGate: "sample_review_gate", samplePhase: "second_sample", sampleLocation: "开发车间", currentOwner: ["user_daqian", "user_zhao", "user_zhangbu"], gateOwner: "user_daqian", finalApprover: "user_yang", plannedShipDate: "2026-06-28", riskStatus: "blocked", nextAction: "确认质量与工艺问题责任人", blockerSummary: "2 个问题阻止寄样" },
  ],
  samples: [
    { id: "sample_212_2", styleId: "style_212", samplePhase: "second_sample", versionName: "二次样", status: "reviewing", location: "开发车间", holder: "李师傅", createdAt: "2026-06-28 10:30", updatedAt: "2026-06-28 11:10", imageList: ["正面", "背面", "领口 / 帽口", "袖口", "下摆抽绳", "压胶缝", "口袋"], videoList: ["整体视频 00:32"], mediaList: [], reviewId: "review_212_second", plannedShipDate: "2026-06-28" },
  ],
  reviews: [
    { id: "review_212_second", styleId: "style_212", sampleId: "sample_212_2", reviewNo: "SR-002", status: "reviewing", gateOwner: "user_daqian", finalApprover: "user_yang", issueIds: ["issue_neck", "issue_hood", "issue_cuff", "issue_tape", "issue_pocket", "issue_label"], finalDecision: "none", exceptionRequest: { reason: "客户会议 / 交期风险 / 样衣用途", riskNote: "重大问题带说明寄样，客户需知晓风险。", applicant: "user_guyao", approver: "user_yang", customerNotified: false, approvalStatus: "待审批" }, timeline: [
      { time: "10:30", type: "green", text: "李师傅 · 样衣制作完成并上传图片" },
      { time: "10:45", type: "black", text: "系统 · 自动生成评审任务 SR-002" },
      { time: "11:00", type: "blue", text: "工业工程部 · 完成独立评审" },
      { time: "11:10", type: "orange", text: "工艺部 · 意见转问题：帽子缝合建议双压线" },
      { time: "11:12", type: "red", text: "品质部 · 重大问题阻止寄样：领口起皱" },
      { time: "11:18", type: "red", text: "工艺部 · 严重问题：压胶剥离风险需复验" },
    ], departmentReviews: [
      { department: "业务部", role: "业务负责人", reviewer: "user_guyao", status: "pass", opinion: "颜色、辅料、物料清单与邮件要求一致。", focusTags: ["客户需求", "技术包/物料清单", "寄样需求"], issueIds: [], reviewedAt: "11:05" },
      { department: "版师", role: "版型评审员", reviewer: "user_xuhaiyan", status: "pass", opinion: "版型符合要求，尺寸符合公差。", focusTags: ["版型", "尺寸", "纸样一致"], issueIds: [], reviewedAt: "11:08" },
      { department: "品质部", role: "质量评审员", reviewer: "user_zhao", status: "fail", opinion: "领口起皱，需整改并复验。", focusTags: ["外观", "历史问题", "测试/复验"], issueIds: ["issue_neck"], reviewedAt: "11:12" },
      { department: "工艺部", role: "工艺评审员", reviewer: "user_chen", status: "needs_improvement", opinion: "帽子缝合建议双压线，压胶参数需确认。", focusTags: ["工艺可行", "压胶稳定", "技术包一致"], issueIds: ["issue_hood", "issue_tape"], reviewedAt: "11:10" },
      { department: "工业工程部", role: "工业工程评审员", reviewer: "user_mike", status: "pass", opinion: "工序可行，无明显瓶颈。", focusTags: ["工时", "瓶颈", "量产产能"], issueIds: [], reviewedAt: "11:00" },
      { department: "打样部", role: "打样反馈人", reviewer: "user_lishifu", status: "pass", opinion: "制作完成，袖口松紧需复核。", focusTags: ["打样异常", "资料清晰", "制作困难"], issueIds: ["issue_cuff"], reviewedAt: "10:45" },
    ] },
  ],
  issues: [
    { id: "issue_neck", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "领口起皱", description: "领口内侧起皱，需要整改并复验。", sourceDepartment: "品质部", relatedArea: "领口 / 帽口", level: "major", shipmentBlocking: true, canShipWithNote: false, owner: "user_zhao", dueDate: "2026-06-28 18:00", status: "in_progress", verifier: "user_zhao", evidence: "图片证据", createdAt: "2026-06-28 11:12", updatedAt: "2026-06-28 11:12" },
    { id: "issue_hood", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "帽子缝合建议双压线", description: "帽子接缝建议改双压线。", sourceDepartment: "工艺部", relatedArea: "帽子接缝", level: "normal", shipmentBlocking: false, canShipWithNote: true, owner: "user_chen", dueDate: "2026-06-29 10:00", status: "not_started", verifier: "user_chen", evidence: "技术包对照", createdAt: "2026-06-28 11:10", updatedAt: "2026-06-28 11:10" },
    { id: "issue_cuff", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "袖口松紧不平", description: "左袖口松紧略不平。", sourceDepartment: "打样部", relatedArea: "左袖口", level: "minor", shipmentBlocking: false, canShipWithNote: true, owner: "user_lishifu", dueDate: "2026-06-29 12:00", status: "not_started", verifier: null, evidence: "视频证据", createdAt: "2026-06-28 10:45", updatedAt: "2026-06-28 10:45" },
    { id: "issue_tape", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "压胶剥离风险未验证", description: "肩缝压胶剥离风险未验证。", sourceDepartment: "工艺部", relatedArea: "压胶缝", level: "critical", shipmentBlocking: true, canShipWithNote: false, owner: "user_zhangbu", dueDate: "2026-06-29 16:00", status: "pending_verification", verifier: "user_zhangbu", evidence: "待测试", createdAt: "2026-06-28 11:18", updatedAt: "2026-06-28 11:18" },
    { id: "issue_pocket", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "口袋位置偏高", description: "客户可能要求下移。", sourceDepartment: "业务部", relatedArea: "口袋", level: "normal", shipmentBlocking: false, canShipWithNote: true, owner: "user_xuhaiyan", dueDate: "2026-06-29 15:00", status: "closed", verifier: "user_xuhaiyan", evidence: "图片证据", createdAt: "2026-06-28 11:00", updatedAt: "2026-06-28 12:00" },
    { id: "issue_label", styleId: "style_212", sampleId: "sample_212_2", reviewId: "review_212_second", title: "洗标位置需确认", description: "洗标位置需要业务确认。", sourceDepartment: "业务部", relatedArea: "洗标", level: "normal", shipmentBlocking: false, canShipWithNote: true, owner: "user_guyao", dueDate: "2026-06-29 13:00", status: "closed", verifier: "user_guyao", evidence: "邮件要求", createdAt: "2026-06-28 11:03", updatedAt: "2026-06-28 12:10" },
  ],
};

window.sampleOSData.sampleWorkers = window.sampleOSData.workers;
